### ISSUE TITLE
No amogus?!?!?!?

### ISSUE THREAD

**Issue by Jarhead20** [ProDCG/OpenAmogus#2]

**Comment by ProDCG** [comment]
WDYM? NO AMOGUS!?!?!?

**Comment by Jarhead20** [comment]
月

**Comment by ProDCG** [comment]
😘😘😘😘

**Comment by Jarhead20** [comment]
👁👄👁

**Comment by ProDCG** [comment]
😶‍🌫️

**Comment by Jarhead20** [comment]
😳

**Comment by ProDCG** [comment]
DID YOU JUST CLOSE THIS ISSUE!?!?!??!?!? HOW DARE YOU

**Comment by Jarhead20** [comment]
%sleep @ProDCG

**Comment by Jarhead20** [comment]
Sorry, I was working on support for roadrunner 1.0 in my amazing tool RRPathGen https://github.com/Jarhead20/RRPathGen , you should check it out and star the repo and contribute, and I must have missclicked and accidentally typed out that sequence of characters randomly.

**Comment by ProDCG** [comment]
wow you suck imagine plugging it here

**Comment by Jarhead20** [comment]
Why you haf 2 be mad :(

**Comment by ProDCG** [comment]
JHEY

**Comment by Srinikal** [comment]
average maturity of a github issue section

**Comment by Jarhead20** [comment]
Mason please respond to my question on discord it's urgent and I might die if you do not respond to my question on discord which reminds me could you please respond to my question which I have sent to you on discord?

Kind regards,
Jared

**Comment by Jarhead20** [comment]
Helo
